### ISSUE TITLE
🐛 google.maps.Map is not a constructor

### ISSUE THREAD

**Issue by RobertVogt** [BeSpunky/angular-google-maps#6]
**Describe the bug**
started receiving this error...

ERROR Error: Uncaught (in promise): TypeError: google.maps.Map is not a constructor
TypeError: google.maps.Map is not a constructor
    at ɵ0 (bespunky-angular-google-maps-core.js:1361:1)
    at bespunky-angular-google-maps-core.js:879:1
    at ZoneDelegate.invoke (zone.js:372:1)
    at Zone.run (zone.js:134:1)
    at NgZone.runOutsideAngular (core.js:28597:1)
    at GoogleMapsApiService.runOutsideAngular (bespunky-angular-google-maps-core.js:541:1)
    at Object.useFactory (bespunky-angular-google-maps-core.js:879:1)
    at NodeInjectorFactory.factory (core.js:11541:1)
    at getNodeInjectable (core.js:3561:1)
    at searchTokensOnInjector (core.js:3498:1)
    at resolvePromise (zone.js:1213:1)
    at zone.js:1283:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.js:28685:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1600:1)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js:1637:1)
defaultErrorLogger @ core.js:6498

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RobertVogt** [comment]
I believe this is because @types/googlemaps has been depricated and replaced with @types/google.maps  and the map you return should look more like this...

const ɵ0 = (element, document) => {
    const { nativeElement: mapElement } = createAndAppendMapElement(element, document);
    const options = new google.maps.MapOptions;
    options.Center = Defaults.Center;
    options.ZoomLevel = Defaults.ZoomLevel;    
    return new google.maps.Map(mapElement, options);
};

...just guessing for now though

**Comment by RobertVogt** [comment]
I resolved my issue...I was using googleapi v=beta in order to use property "isFractionalZoomEnabled"

Google deprecated this version and when I changed it to 3.51 everything started working again.
